cmd_/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.o := /opt/toolchains//crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin/arm-buildroot-linux-gnueabi-gcc -Wp,-MD,/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/.stub.o.d -nostdinc -isystem /opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/lib/gcc/arm-buildroot-linux-gnueabi/5.5.0/include -I./arch/arm/include -Iarch/arm/include/generated/uapi -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-bcm963xx/include -Iarch/arm/plat-bcm63xx/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -fno-PIE -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DPHY_CROSSBAR -DMAC_UNIMAC -DPHY_6846_EGPHY -DPHY_EXT1 -I/framework -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/include/drv/phys -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/include/drv/mdio -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/include/drv/unimac -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/include/pmc -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/lport -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/lport/ag -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/bcmdrivers/opensource/net/enet/shared -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/bcmdrivers/opensource/include/bcm963xx -I/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/include/bcm963xx @/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/kernel/linux-4.1/rdp_flags.txt    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(stub)"  -D"KBUILD_MODNAME=KBUILD_STR(stub)" -c -o /home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.o /home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.c

source_/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.o := /home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.c

deps_/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.o := \

/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.o: $(deps_/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.o)

$(deps_/home/zyntax/firmwarehacks/devel/bcmopen-consumerworks/bcm963xx/shared/opensource/drv/stub.o):
