
 
#define SUPPORT_DM_HYBRID 1
 
#define DMP_BASELINE_1 1
 
#define DMP_X_BROADCOM_COM_BASELINE_1 1
 
#define DMP_ETHERNETLAN_1 1
 
#define DMP_X_BROADCOM_COM_DEBUG_1 1
 
#define DMP_X_BROADCOM_COM_SECURITY_1 1
 
#define DMP_DEVICEASSOCIATION_1 1
 
#define DMP_IPPING_1 1
 
#define DMP_DUSTATECHNGCOMPLPOLICY_1 1
 
#define DMP_DEVICE2_BASELINE_1 1
 
#define DMP_DEVICE2_X_BROADCOM_COM_BASELINE_1 1
 
#define DMP_DEVICE2_BASELINE_2 1
 
#define DMP_DEVICE2_BASELINE_3 1
 
#define DMP_DEVICE2_IPINTERFACE_1 1
 
#define DMP_DEVICE2_IPINTERFACE_2 1
 
#define DMP_DEVICE2_ETHERNETLINK_1 1
 
#define DMP_DEVICE2_ETHERNETINTERFACE_1 1
 
#define DMP_DEVICE2_VLANTERMINATION_1 1
 
#define DMP_DEVICE2_PPPINTERFACE_1 1
 
#define DMP_DEVICE2_PPPINTERFACE_2 1
 
#define DMP_DEVICE2_IPPING_1 1
 
#define DMP_DEVICE2_TRACEROUTE_1 1
 
#define DMP_DEVICE2_ROUTING_1 1
 
#define DMP_DEVICE2_ROUTING_2 1
 
#define DMP_DEVICE2_DUSTATECHNGCOMPLPOLICY_1 1
 
#define SUPPORT_ETHWAN 1
 
#define DMP_ETHERNETWAN_1 1
 
#define SUPPORT_TMCTL 1
 
#define SUPPORT_RDPA 1
 
#define DMP_X_BROADCOM_COM_RDPA_1 1
 
#define DMP_X_BROADCOM_COM_PONWAN_1 1
 
#define DMP_X_BROADCOM_COM_EPONWAN_1 1
 
#define DMP_X_BROADCOM_COM_PONWAN_1 1
 
#define DMP_X_BROADCOM_COM_GPONWAN_1 1
 
#define DMP_X_BROADCOM_COM_GPONRG_OMCI_FULL_1 1
 
#define SUPPORT_IPV6 1
 
#define DMP_X_BROADCOM_COM_DEV2_IPV6_1 1
 
#define DMP_DEVICE2_DSLITE_1 1
 
#define DMP_DEVICE2_DSLITE_2 1
 
#define DMP_DEVICE2_IPV6RD_1 1
 
#define DMP_DEVICE2_IPV6INTERFACE_1 1
 
#define DMP_DEVICE2_IPV6ROUTING_1 1
 
#define DMP_DEVICE2_DHCPV6CLIENT_1 1
 
#define DMP_DEVICE2_DHCPV6CLIENTSERVERIDENTITY_1 1
 
#define DMP_DEVICE2_DHCPV6SERVER_1 1
 
#define DMP_DEVICE2_DHCPV6SERVERADV_1 1
 
#define DMP_DEVICE2_DHCPV6SERVERCLIENTINFO_1 1
 
#define DMP_DEVICE2_NEIGHBORDISCOVERY_1 1
 
#define DMP_DEVICE2_ROUTERADVERTISEMENT_1 1
 
#define DMP_X_ITU_ORG_GPON_1 1
 
#define DMP_X_BROADCOM_COM_GPON_1 1
 
#define DMP_DEVICE2_OPTICAL_1 1
 
#define DMP_X_BROADCOM_COM_XPON_1 1
 
#define BRCM_OMCI 1
 
#define SUPPORT_EBTABLES 1
 
#define SUPPORT_IPP 1
 
#define DMP_X_BROADCOM_COM_IPPRINTING_1 1
 
#define SUPPORT_BLOGCTL 1
 
#define SUPPORT_FCCTL 1
 
#define SUPPORT_ETHSWCTL 1
 
#define SUPPORT_PWRMNGT 1
 
#define DMP_X_BROADCOM_COM_PWRMNGT_1 1
 
#define SUPPORT_ETH_PWRSAVE 1
 
#define SUPPORT_ENERGY_EFFICIENT_ETHERNET 1
 
#define SUPPORT_GPONCTL 1
 
#define DMP_X_BROADCOM_COM_EPON_1 1
 
#define DMP_X_BROADCOM_COM_MCAST_1 1
 
#define DMP_X_BROADCOM_COM_IGMPSNOOP_1 1
 
#define DMP_X_BROADCOM_COM_MLDSNOOP_1 1
 
#define DMP_X_BROADCOM_COM_DCSP_MCAST_REMARK_1 1
 
#define SUPPORT_IGMP 1
 
#define DMP_X_BROADCOM_COM_IGMP_1 1
 
#define SUPPORT_MLD 1
 
#define DMP_X_BROADCOM_COM_MLD_1 1
 
#define SUPPORT_NF_NAT 1
 
#define SUPPORT_NF_FIREWALL 1
 
#define SUPPORT_PPTP 1
 
#define SUPPORT_NF_MANGLE 1
 
#define SUPPORT_INTF_GROUPING 1
 
#define SUPPORT_PORT_MAP 1
 
#define DMP_BRIDGING_1 1
 
#define SUPPORT_WANVLANMUX 1
 
#define SUPPORT_VLANCTL 1
 
#define SUPPORT_LANVLAN 1
 
#define SUPPORT_QOS 1
 
#define DMP_QOS_1 1
 
#define DMP_QOSDYNAMICFLOW_1 1
 
#define DMP_X_BROADCOM_COM_QOS_1 1
 
#define DMP_X_BROADCOM_COM_TM_1 1
 
#define SUPPORT_POLICING 1
 
#define HW_POLICING 1
 
#define CONFIG_BCM_VLAN_AGGREGATION 1
 
#define CONFIG_BCM_KF_VLAN_AGGREGATION 1
 
#define SUPPORT_DEBUG_TOOLS 1
 
#define COMPRESSED_CONFIG_FILE 1
 
#define CMS_CONFIG_COMPAT 1

 

// -DSUPPORT_DM_HYBRID -DDMP_BASELINE_1 -DDMP_X_BROADCOM_COM_BASELINE_1 -DDMP_ETHERNETLAN_1 -DDMP_X_BROADCOM_COM_DEBUG_1 -DDMP_X_BROADCOM_COM_SECURITY_1 -DDMP_DEVICEASSOCIATION_1 -DDMP_IPPING_1 -DDMP_DUSTATECHNGCOMPLPOLICY_1 -DDMP_DEVICE2_BASELINE_1 -DDMP_DEVICE2_X_BROADCOM_COM_BASELINE_1 -DDMP_DEVICE2_BASELINE_2 -DDMP_DEVICE2_BASELINE_3 -DDMP_DEVICE2_IPINTERFACE_1 -DDMP_DEVICE2_IPINTERFACE_2 -DDMP_DEVICE2_ETHERNETLINK_1 -DDMP_DEVICE2_ETHERNETINTERFACE_1 -DDMP_DEVICE2_VLANTERMINATION_1 -DDMP_DEVICE2_PPPINTERFACE_1 -DDMP_DEVICE2_PPPINTERFACE_2 -DDMP_DEVICE2_IPPING_1 -DDMP_DEVICE2_TRACEROUTE_1 -DDMP_DEVICE2_ROUTING_1 -DDMP_DEVICE2_ROUTING_2 -DDMP_DEVICE2_DUSTATECHNGCOMPLPOLICY_1 -DSUPPORT_ETHWAN -DDMP_ETHERNETWAN_1 -DSUPPORT_TMCTL -DSUPPORT_RDPA -DDMP_X_BROADCOM_COM_RDPA_1 -DDMP_X_BROADCOM_COM_PONWAN_1 -DDMP_X_BROADCOM_COM_EPONWAN_1 -DDMP_X_BROADCOM_COM_PONWAN_1 -DDMP_X_BROADCOM_COM_GPONWAN_1 -DDMP_X_BROADCOM_COM_GPONRG_OMCI_FULL_1 -DSUPPORT_IPV6 -DDMP_X_BROADCOM_COM_DEV2_IPV6_1 -DDMP_DEVICE2_DSLITE_1 -DDMP_DEVICE2_DSLITE_2 -DDMP_DEVICE2_IPV6RD_1 -DDMP_DEVICE2_IPV6INTERFACE_1 -DDMP_DEVICE2_IPV6ROUTING_1 -DDMP_DEVICE2_DHCPV6CLIENT_1 -DDMP_DEVICE2_DHCPV6CLIENTSERVERIDENTITY_1 -DDMP_DEVICE2_DHCPV6SERVER_1 -DDMP_DEVICE2_DHCPV6SERVERADV_1 -DDMP_DEVICE2_DHCPV6SERVERCLIENTINFO_1 -DDMP_DEVICE2_NEIGHBORDISCOVERY_1 -DDMP_DEVICE2_ROUTERADVERTISEMENT_1 -DDMP_X_ITU_ORG_GPON_1 -DDMP_X_BROADCOM_COM_GPON_1 -DDMP_DEVICE2_OPTICAL_1 -DDMP_X_BROADCOM_COM_XPON_1 -DBRCM_OMCI -DSUPPORT_EBTABLES -DSUPPORT_IPP -DDMP_X_BROADCOM_COM_IPPRINTING_1 -DSUPPORT_BLOGCTL -DSUPPORT_FCCTL -DSUPPORT_ETHSWCTL -DSUPPORT_PWRMNGT -DDMP_X_BROADCOM_COM_PWRMNGT_1 -DSUPPORT_ETH_PWRSAVE -DSUPPORT_ENERGY_EFFICIENT_ETHERNET -DSUPPORT_GPONCTL -DDMP_X_BROADCOM_COM_EPON_1 -DDMP_X_BROADCOM_COM_MCAST_1 -DDMP_X_BROADCOM_COM_IGMPSNOOP_1 -DDMP_X_BROADCOM_COM_MLDSNOOP_1 -DDMP_X_BROADCOM_COM_DCSP_MCAST_REMARK_1 -DSUPPORT_IGMP -DDMP_X_BROADCOM_COM_IGMP_1 -DSUPPORT_MLD -DDMP_X_BROADCOM_COM_MLD_1 -DSUPPORT_NF_NAT -DSUPPORT_NF_FIREWALL -DSUPPORT_PPTP -DSUPPORT_NF_MANGLE -DSUPPORT_INTF_GROUPING -DSUPPORT_PORT_MAP -DDMP_BRIDGING_1 -DSUPPORT_WANVLANMUX -DSUPPORT_VLANCTL -DSUPPORT_LANVLAN -DSUPPORT_QOS -DDMP_QOS_1 -DDMP_QOSDYNAMICFLOW_1 -DDMP_X_BROADCOM_COM_QOS_1 -DDMP_X_BROADCOM_COM_TM_1 -DSUPPORT_POLICING -DHW_POLICING -DCONFIG_BCM_VLAN_AGGREGATION -DCONFIG_BCM_KF_VLAN_AGGREGATION -DSUPPORT_DEBUG_TOOLS -DCOMPRESSED_CONFIG_FILE -DCMS_CONFIG_COMPAT

